/* Generated By:JavaCC: Do not edit this line. BooleanModelParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
#ifndef BOOLEANMODELPARSERCONSTANTS_H
#define BOOLEANMODELPARSERCONSTANTS_H

  /** End of File. */
const  int _EOF = 0;
  /** RegularExpression Id. */
const  int NOT = 8;
  /** RegularExpression Id. */
const  int AND = 9;
  /** RegularExpression Id. */
const  int OR = 10;
  /** RegularExpression Id. */
const  int IFF = 11;
  /** RegularExpression Id. */
const  int IMPLIES = 12;
  /** RegularExpression Id. */
const  int LPAR = 13;
  /** RegularExpression Id. */
const  int RPAR = 14;
  /** RegularExpression Id. */
const  int LBRACKET = 15;
  /** RegularExpression Id. */
const  int RBRACKET = 16;
  /** RegularExpression Id. */
const  int DOT = 17;
  /** RegularExpression Id. */
const  int COMMA = 18;
  /** RegularExpression Id. */
const  int COLON = 19;
  /** RegularExpression Id. */
const  int SEMICOLON = 20;
  /** RegularExpression Id. */
const  int ASSIGN = 21;
  /** RegularExpression Id. */
const  int ASTERISK = 22;
  /** RegularExpression Id. */
const  int TRUE = 23;
  /** RegularExpression Id. */
const  int FALSE = 24;
  /** RegularExpression Id. */
const  int IDENTIFIER = 25;
  /** RegularExpression Id. */
const  int NUMBER = 26;
  /** RegularExpression Id. */
const  int LETTER = 27;
  /** RegularExpression Id. */
const  int DIGIT = 28;
  /** RegularExpression Id. */
const  int NONZ_DIGIT = 29;
  /** RegularExpression Id. */
const  int BIN_DIGIT = 30;
  /** RegularExpression Id. */
const  int BLANKS = 31;
  /** RegularExpression Id. */
const  int ILLEGAL_CHAR = 32;

  /** Lexical state. */
const  int DEFAULT = 0;

  /** Literal token values. */
  static JAVACC_CHAR_TYPE tokenImage_arr_0[] = 
{0x3c, 0x45, 0x4f, 0x46, 0x3e, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_1[] = 
{0x22, 0x20, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_2[] = 
{0x22, 0x9, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_3[] = 
{0x22, 0xa, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_4[] = 
{0x22, 0xd, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_5[] = 
{0x22, 0xd, 0xa, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_6[] = 
{0x22, 0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x36, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_7[] = 
{0x22, 0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x37, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_8[] = 
{0x22, 0x7e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_9[] = 
{0x22, 0x26, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_10[] = 
{0x22, 0x7c, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_11[] = 
{0x22, 0x3d, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_12[] = 
{0x22, 0x2d, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_13[] = 
{0x22, 0x28, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_14[] = 
{0x22, 0x29, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_15[] = 
{0x22, 0x5b, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_16[] = 
{0x22, 0x5d, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_17[] = 
{0x22, 0x2e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_18[] = 
{0x22, 0x2c, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_19[] = 
{0x22, 0x3a, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_20[] = 
{0x22, 0x3b, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_21[] = 
{0x22, 0x3a, 0x3d, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_22[] = 
{0x22, 0x2a, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_23[] = 
{0x22, 0x74, 0x72, 0x75, 0x65, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_24[] = 
{0x22, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_25[] = 
{0x22, 0x3c, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x45, 0x52, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_26[] = 
{0x22, 0x3c, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_27[] = 
{0x22, 0x3c, 0x4c, 0x45, 0x54, 0x54, 0x45, 0x52, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_28[] = 
{0x22, 0x3c, 0x44, 0x49, 0x47, 0x49, 0x54, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_29[] = 
{0x22, 0x3c, 0x4e, 0x4f, 0x4e, 0x5a, 0x5f, 0x44, 0x49, 0x47, 0x49, 0x54, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_30[] = 
{0x22, 0x3c, 0x42, 0x49, 0x4e, 0x5f, 0x44, 0x49, 0x47, 0x49, 0x54, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_31[] = 
{0x22, 0x3c, 0x42, 0x4c, 0x41, 0x4e, 0x4b, 0x53, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_32[] = 
{0x22, 0x3c, 0x49, 0x4c, 0x4c, 0x45, 0x47, 0x41, 0x4c, 0x5f, 0x43, 0x48, 0x41, 0x52, 0x3e, 0x22, 0};
  static JAVACC_STRING_TYPE tokenImage[] = {
tokenImage_arr_0, 
tokenImage_arr_1, 
tokenImage_arr_2, 
tokenImage_arr_3, 
tokenImage_arr_4, 
tokenImage_arr_5, 
tokenImage_arr_6, 
tokenImage_arr_7, 
tokenImage_arr_8, 
tokenImage_arr_9, 
tokenImage_arr_10, 
tokenImage_arr_11, 
tokenImage_arr_12, 
tokenImage_arr_13, 
tokenImage_arr_14, 
tokenImage_arr_15, 
tokenImage_arr_16, 
tokenImage_arr_17, 
tokenImage_arr_18, 
tokenImage_arr_19, 
tokenImage_arr_20, 
tokenImage_arr_21, 
tokenImage_arr_22, 
tokenImage_arr_23, 
tokenImage_arr_24, 
tokenImage_arr_25, 
tokenImage_arr_26, 
tokenImage_arr_27, 
tokenImage_arr_28, 
tokenImage_arr_29, 
tokenImage_arr_30, 
tokenImage_arr_31, 
tokenImage_arr_32, 
  };

#endif
